<a href="https://colab.research.google.com/github/samidha-sudhi/Python-Basics/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#NumPy

In [ ]:
import numpy as np
array_1 = np.array([1,2,3,4,5])
print(array_1)

[1 2 3 4 5]


In [ ]:
# Properties associated with Numpy array
print("Array 1, NDim", array_1.ndim)
print("Array 1, Shape", array_1.shape)
print("Array 1, Size", array_1.size)
print("Array 1, Data type", array_1.dtype)


Array 1, NDim 1
Array 1, Shape (5,)
Array 1, Size 5
Array 1, Data type int64


In [ ]:
# Two dimentional array
array_2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(array_2)
print("Array_2, NDim",array_2.ndim)
print("Array_2, Size",array_2.size)
print("Array_2, Shape",array_2.shape)
print("Array_2, Data Type",array_2.dtype)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Array_2, NDim 2
Array_2, Size 10
Array_2, Shape (2, 5)
Array_2, Data Type int64


In [ ]:
# Three dimentional array
array_3 = np.array([[1,2,3,4,5],[6,7,8,9,10], [11,12,13,14,15]])
print(array_3)
print("Array_3, NDim",array_3.ndim)
print("Array_3, Size",array_3.size)
print("Array_3, Shape",array_3.shape)
print("Array_3, Data Type",array_3.dtype)
print("Array_3, Reshape", array_3.reshape(5,3))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
Array_3, NDim 2
Array_3, Size 15
Array_3, Shape (3, 5)
Array_3, Data Type int64
Array_3, Reshape [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


In [ ]:
# Indexing and Slicing Numpy
data = np.array([1,2,3])
data

array([1, 2, 3])

In [ ]:
data[2]

np.int64(3)

In [ ]:
data[0:2]

array([1, 2])

## Methods to create an array fast

In [ ]:
np.zeros(10, dtype=np.int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
np.ones(5, dtype=np.int64)

array([1, 1, 1, 1, 1])

In [ ]:
np.arange(2,20,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
np.linspace(0,10,num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [ ]:
# Adding and sorting elements in a numpy array
array_4 = np.array([2,1,8,3,2,10,9,4])
np.sort(array_4)

array([ 1,  2,  2,  3,  4,  8,  9, 10])

In [ ]:
# Arrays can be concatenated
a5 = np.array([[1,2],[3,4]])
a6 = np.array([[5,6]])
a7 = np.concatenate((a5,a6), axis=0)
print(a7)
print('----')


[[1 2]
 [3 4]
 [5 6]]
----


In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])

# Concatenate along axis 0 (rows)
c = np.concatenate((a, b), axis=0)
print("Concatenated along axis 0:\n", c)

Concatenated along axis 0:
 [[1 2]
 [3 4]
 [5 6]]


In [ ]:
#Array operations
import numpy as np

array1=np.array([1,2])
array2=np.array([2,3])
array3=np.ones(2,dtype=int)
array4=np.arange(2,20,2)
array5=3.14*array4

print(array1,array2,array3)
print(array4)
print(f'addition={array1+array2}')
print(f'substraction={array2-array3}')
print(f'multiplication={array1*array3}')
print(f'division={array2/array1}')
print(f'array4 addition={array4.sum()}')
print(f'array4 min= {array4.min()}')
print(f'array4_max = {array4.max()}')
print(f'array4_mean ={array4.mean()}')
print(f'array5 = {array5}')
print(f'array5 > 20 = {array5>20}')
print(f'{(array5>20) & (array5<40)}')
print(f'{array5[(array5>20) & (array5<40)]}')
#print(f'{(20<{array5}<40)}')

[1 2] [2 3] [1 1]
[ 2  4  6  8 10 12 14 16 18]
addition=[3 5]
substraction=[1 2]
multiplication=[1 2]
division=[2.  1.5]
array4 addition=90
array4 min= 2
array4_max = 18
array4_mean =10.0
array5 = [ 6.28 12.56 18.84 25.12 31.4  37.68 43.96 50.24 56.52]
array5 > 20 = [False False False  True  True  True  True  True  True]
[False False False  True  True  True False False False]
[25.12 31.4  37.68]


In [ ]:
# save array in file
array6=np.array([1,2,3,4,5,6,7,8])
np.save('sixth_array', array6)
! ls
np.load('sixth_array.npy')
np.savetxt('sixth_array_csv.csv', array6)
! ls
! cat sixth_array_csv.csv
array7=np.loadtxt('sixth_array_csv.csv')
array7

sample_data  sixth_array_csv.csv  sixth_array.npy
sample_data  sixth_array_csv.csv  sixth_array.npy
1.000000000000000000e+00
2.000000000000000000e+00
3.000000000000000000e+00
4.000000000000000000e+00
5.000000000000000000e+00
6.000000000000000000e+00
7.000000000000000000e+00
8.000000000000000000e+00


array([1., 2., 3., 4., 5., 6., 7., 8.])

# File Handling in Python

*   read()



In [ ]:
#file = open("/sample_data/test1.txt", "r")
#content = file.read()

with open ('/content/sample_data/test1.txt' 'r') as f:
    file_content = f.read()
print(file_content)

FileNotFoundError: [Errno 2] No such file or directory: '/content/sample_data/test1.txtr'

# Python Modules

## Math Module

In [ ]:
import math
print(math.sqrt(16))
print(math.factorial(5))
print(math.sin(math.pi))
print(math.cos(math.pi))
print(math.ceil(-3.8))
print(math.floor(-2.3))
print(math.exp(2))
print(math.log(10))

4.0
120
1.2246467991473532e-16
-1.0
-3
-3
7.38905609893065
2.302585092994046


## Random Module

In [ ]:
import random
print(random.randint(1,5))
print(random.random())
print(random.choice([1,2,4,6,8]))
items = ['a','b','c','d']
print(random.shuffle(items))

1
0.0871548721015325
1
None


## Datetime Module

In [ ]:
import datetime
print(datetime.datetime.now())
print(datetime.date.today())
date1 = datetime.date(25,4,10)
date2 = datetime.date(25,6,3)
print((date2-date1).days)

2025-06-14 21:10:30.735948
2025-06-14
54


## User Defined Modules

# Functions in Python

## Lambda Functions

In [ ]:
#lambda arguments: expressions
# simple addition
def add(x,y):
  return x+y
print(add(5,3))

#lambda function
add = lambda x,y: x+y
print(add(5,3))

8
8


In [ ]:
# Define lambda function to square a number
square = lambda x: x**2
print(square(5))

25


In [ ]:
# Sorting a list of Tuples
pairs = [(1,'one'), (3,'three'), (4,'four'), (2,'two')]
pairs.sort(key= lambda x:x[0])
print(pairs)

[(1, 'one'), (2, 'two'), (3, 'three'), (4, 'four')]


## Map Function
### map() Function

Syntax:map(function, iterable)

In [ ]:
# Squaring number in a list
# Define a list of numbers
numbers = [1,2,3,4,5]

# Use map to square each number in the list
squared_numbers = map(lambda x: x**2, numbers)
print(list(squared_numbers))

[1, 4, 9, 16, 25]


In [ ]:
# Converting Fahrenheit to Celsius
# Define a list of temperatures in Fahrenheit
# Rounding to 2 decimal digits
F_temp = [20, 32,70,90,110,64,55]

C_temp = map(lambda f: round((f-32)*5/9,2), F_temp)

print(list(C_temp))

[-6.67, 0.0, 21.11, 32.22, 43.33, 17.78, 12.78]


In [ ]:
# Capitalize string using map function
strings = ['apple', 'banana', 'orange', 'grapes']
capatalized_strings = map(str.capitalize, strings)
print(list(capatalized_strings))


['Apple', 'Banana', 'Orange', 'Grapes']


TypeError: count() takes at least 1 argument (0 given)

In [ ]:
# Find length of strings in a list
strings = ['apple', 'banana', 'orange', 'grapes']

#length_strings = map(len, strings) # Method 1

length_strings = map(lambda x: len(x), strings) # Method 2

print(list(length_strings))

[5, 6, 6, 6]


## Mapping with multiple iterables

In [ ]:
# Define two lists of numbers
numbers1 = [1,2,3]
numbers2 = [4,5,6]

# Use map() to add corresponding elements of both lists
sums = map(lambda x, y: x+y, numbers1, numbers2)

#Convert the map object to a list
sums_list = list(sums)

print(sums_list)

[5, 7, 9]


##Filter function
###filter ()

In [ ]:
#Filter even numbers
#Define a list of numbers
numbers = [1,2,3,4,5,6,7,8,9]

#Use filter() to keep only even numbers
even_numbers = filter(lambda x:x%2 ==0, numbers)

print(list(even_numbers))

[2, 4, 6, 8]


In [ ]:
#Filter greater than 4 chars
#Define a list of strings
strings = ['apple','banana','grapes','orange','pear', 'kiwi']

#Filter strings greater than 4 chars
strings_greater4 = filter(lambda x: len(x)>4, strings)

print(list(strings_greater4))

['apple', 'banana', 'grapes', 'orange']


In [ ]:
#Filter positive numbers
#Define a list of numbers
numbers = [-1,2,3,-4,-5,6,7,9]

#Filter positive numbers
positive_numbers = filter(lambda x: x>0, numbers)

print(list(positive_numbers))

[2, 3, 6, 7, 9]


In [ ]:
#Remove None values from list
# Define a list of numbers
values = [1,2,None,4,5,None,6,None]

#Filter not none values
filter_none = filter(lambda x: x is not None, values)

print(list(filter_none))

[1, 2, 4, 5, 6]


In [ ]:
#Define a function to filter strings starting with 'a'
strings = ['apple', 'orange', 'kiwi', 'apricot', 'aspharagues']

#option 1
#strings_with_a = filter(lambda x: x[0]=='a', strings)

#option 2 ensuring comparison using lower case
#strings_with_a = filter(lambda x: x[0].lower()=='a', strings)

#option 3 using startswith function
strings_with_a = filter(lambda x: x.startswith('a'), strings)

print(list(strings_with_a))

['apple', 'apricot', 'aspharagues']


## Reduce Function

### reduce()

In [ ]:
# functools.reduce(function, iterable[,initializer])

In [ ]:
import functools
from functools import reduce

### Summing numbers in a list

In [ ]:
# Define numbers in a list
numbers = [1,2,3,4,5]

# Use reduce to calculate sum of numbers
sum_of_numbers = functools.reduce(lambda x,y: x+y, numbers)

print(sum_of_numbers)

15


## Find the maximum number in a list

In [ ]:
# Define numbers in a list
numbers = [3,4,5,9,2,7]

#Find the maximum number
maximum_number = functools.reduce(lambda x,y: x if x>y else y, numbers)

print(maximum_number)

9


In [ ]:
# Concatenating strings in a lit
strings = ['hello', 'this', 'is', 'simple', 'function']

#Concatenate strings
concatenate_strings = reduce(lambda x, y: x+' '+y, strings)

print(concatenate_strings)

hello this is simple function


In [ ]:
# Computing factorial for a number
#Define a number
n =5
factorial_n = functools.reduce(lambda n, y: n*y, range(1, (n+1)))
factorial_n = mapfunctools.reduce(lambda n, y: n*y, range(1, (n+1)))

print(factorial_n)

120


In [ ]:
# Performing custom rolling computation

In [ ]:
# Define a list of numbers
numbers = {10,20,30,40,50}

result = functools.reduce(lambda x,y: (x[0]+y, y), numbers,(0,0))

print(result)

(150, 30)
